version: 2
jobs:
  build:
    docker:
      # 環境情報を追加
      - image: circleci/ruby:2.5.5-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: eventmag
          RAILS_ENV: test
      - image: circleci/postgres:11.2
        environment:
          POSTGRES_USER: eventmag
          POSTGRES_DB: eventmag_test
          POSTGRES_PASSWORD: ""

    # ディレクトリ情報を移動
    working_directory: ~/eventmag
    steps:
      - checkout

      # bundler2.0.1をinstall
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Database setup
      - run:
          name: Database setup
          command: |
            # bin/rails db:create
            # bin/rails db:schema:load --trace

      # run tests!
      # rubocopを実行
      - run:
          name: rubocop
          command: bundle exec rubocop

      # Rspec,System specを実行
      - run:
          name: run tests
          command: |
            mkdir /tmp/test_results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test_results/rspec.xml \
                            --format progress \
                            "${TEST_FILES}"

      # Save test results for timing analysis
      - store_test_results:
          path: /tmp/test_results
      - store_artifacts:
          path: /tmp/test_results
          destination: test_results